CREATE DATABASE IF NOT EXISTS slep_flota_db;
USE slep_flota_db;

-- Tabla de Usuarios (Funcionarios / Unidades)
CREATE TABLE IF NOT EXISTS USUARIO (
    usu_id INT AUTO_INCREMENT PRIMARY KEY,
    usu_unidad VARCHAR(100) NOT NULL UNIQUE,
    usu_password VARCHAR(255) NOT NULL
);

-- Tabla de Administradores
CREATE TABLE IF NOT EXISTS ADMINISTRADOR (
    adm_id INT AUTO_INCREMENT PRIMARY KEY,
    adm_correo VARCHAR(100) NOT NULL UNIQUE,
    adm_password VARCHAR(255) NOT NULL
);

-- Tabla de Choferes
CREATE TABLE IF NOT EXISTS CHOFER (
    cho_correoinstitucional VARCHAR(100) PRIMARY KEY,
    cho_nombre VARCHAR(100) NOT NULL,
    cho_activo BOOLEAN DEFAULT TRUE
);

-- Tabla de Vehículos
CREATE TABLE IF NOT EXISTS VEHICULO (
    vehi_patente VARCHAR(10) PRIMARY KEY,
    vehi_marca VARCHAR(50) NOT NULL,
    vehi_modelo VARCHAR(50) NOT NULL,
    vehi_anio INT,
    vehi_color VARCHAR(30),
    vehi_tipo VARCHAR(50) NOT NULL,
    vehi_motor VARCHAR(50),
    vehi_chasis VARCHAR(50),
    vehi_capacidad INT NOT NULL COMMENT 'Capacidad Pasajeros',
    vehi_capacidad_carga VARCHAR(50) COMMENT 'Capacidad kg-mt3',
    vehi_inventario VARCHAR(50),
    vehi_propietario VARCHAR(100) DEFAULT 'SERVICIO LOCAL DE LLANQUIHUE',
    vehi_resolucion VARCHAR(100),
    vehi_lugaraparcamiento VARCHAR(150),
    vehi_poliza VARCHAR(100),
    vehi_multas TEXT,
    vehi_estado ENUM('DISPONIBLE', 'EN RUTA', 'MANTENCION') DEFAULT 'DISPONIBLE'
);

-- Tabla de Bitácora de Vehículo
CREATE TABLE IF NOT EXISTS BITACORA_VEHICULO (
    bit_id INT AUTO_INCREMENT PRIMARY KEY,
    bit_patentevehiculofk VARCHAR(10) NOT NULL,
    bit_fecha DATETIME NOT NULL,
    bit_funcionario_responsable VARCHAR(100) NOT NULL,
    bit_kilometraje INT NOT NULL,
    bit_evento VARCHAR(100) NOT NULL,
    bit_mecanico VARCHAR(100),
    bit_valor_mantencion INT DEFAULT 0,
    bit_observaciones TEXT,
    FOREIGN KEY (bit_patentevehiculofk) REFERENCES VEHICULO(vehi_patente) ON DELETE CASCADE
);


-- Tabla de Tipos de Pasajero
CREATE TABLE IF NOT EXISTS TIPO_PASAJERO (
    tip_id INT AUTO_INCREMENT PRIMARY KEY,
    tip_nombre VARCHAR(50) NOT NULL
);

-- Tabla de Comunas
CREATE TABLE IF NOT EXISTS COMUNA (
    com_id INT AUTO_INCREMENT PRIMARY KEY,
    com_nombre VARCHAR(100) NOT NULL
);

-- Tabla de Lugares
CREATE TABLE IF NOT EXISTS LUGAR (
    lug_id INT AUTO_INCREMENT PRIMARY KEY,
    lug_nombre VARCHAR(150) NOT NULL,
    lug_comunafk INT NOT NULL,
    FOREIGN KEY (lug_comunafk) REFERENCES COMUNA(com_id)
);

-- Tabla de Solicitudes
CREATE TABLE IF NOT EXISTS SOLICITUDES (
    sol_id VARCHAR(36) PRIMARY KEY,
    sol_nombresolicitante VARCHAR(100) NOT NULL,
    sol_fechasalida DATETIME NOT NULL,
    sol_fechallegada DATETIME NOT NULL,
    sol_estado ENUM('PENDIENTE', 'APROBADA', 'RECHAZADA', 'FINALIZADA') DEFAULT 'PENDIENTE',
    sol_unidad VARCHAR(100) NOT NULL,
    sol_motivo TEXT NOT NULL,
    sol_itinerario TEXT,
    sol_tipo VARCHAR(50),
    sol_requierechofer BOOLEAN DEFAULT FALSE,
    sol_kmestimado INT DEFAULT 0,
    sol_observacionrechazo TEXT,
    
    -- Foreign Keys
    sol_idusuariofk INT,
    sol_patentevehiculofk VARCHAR(10),
    sol_correochoferfk VARCHAR(100),
    sol_idadminfk INT,
    
    FOREIGN KEY (sol_idusuariofk) REFERENCES USUARIO(usu_id),
    FOREIGN KEY (sol_patentevehiculofk) REFERENCES VEHICULO(vehi_patente),
    FOREIGN KEY (sol_correochoferfk) REFERENCES CHOFER(cho_correoinstitucional),
    FOREIGN KEY (sol_idadminfk) REFERENCES ADMINISTRADOR(adm_id)
);

-- Tabla de Pasajeros de Solicitud
CREATE TABLE IF NOT EXISTS PASAJEROS (
    pas_id INT AUTO_INCREMENT PRIMARY KEY,
    pas_nombre VARCHAR(100) NOT NULL,
    pas_idsolicitudfk VARCHAR(36) NOT NULL,
    pas_idtipofk INT,
    FOREIGN KEY (pas_idsolicitudfk) REFERENCES SOLICITUDES(sol_id) ON DELETE CASCADE,
    FOREIGN KEY (pas_idtipofk) REFERENCES TIPO_PASAJERO(tip_id)
);

-- Tabla de Establecimientos (Colegios Oficiales)
CREATE TABLE IF NOT EXISTS ESTABLECIMIENTO (
    est_id INT PRIMARY KEY COMMENT 'RBD o ID Oficial',
    est_nombre VARCHAR(150) NOT NULL,
    est_comunafk INT NOT NULL,
    FOREIGN KEY (est_comunafk) REFERENCES COMUNA(com_id)
);

-- Tabla de Destinos de Solicitud
CREATE TABLE IF NOT EXISTS SOLICITUD_DESTINO (
    sde_id INT AUTO_INCREMENT PRIMARY KEY,
    sde_solicitudfk VARCHAR(36) NOT NULL,
    sde_lugarfk INT,
    sde_establecimientofk INT,
    FOREIGN KEY (sde_solicitudfk) REFERENCES SOLICITUDES(sol_id) ON DELETE CASCADE,
    FOREIGN KEY (sde_lugarfk) REFERENCES LUGAR(lug_id),
    FOREIGN KEY (sde_establecimientofk) REFERENCES ESTABLECIMIENTO(est_id)
);

-- Insertar Datos Iniciales (Seeders)
-- Tipos de Pasajero
INSERT INTO TIPO_PASAJERO (tip_nombre) VALUES ('Estudiante') ON DUPLICATE KEY UPDATE tip_nombre=tip_nombre;
INSERT INTO TIPO_PASAJERO (tip_nombre) VALUES ('Funcionario') ON DUPLICATE KEY UPDATE tip_nombre=tip_nombre;
INSERT INTO TIPO_PASAJERO (tip_nombre) VALUES ('Apoderado') ON DUPLICATE KEY UPDATE tip_nombre=tip_nombre;

-- Comunas Base
INSERT INTO COMUNA (com_nombre) VALUES ('Llanquihue') ON DUPLICATE KEY UPDATE com_nombre=com_nombre;
INSERT INTO COMUNA (com_nombre) VALUES ('Puerto Varas') ON DUPLICATE KEY UPDATE com_nombre=com_nombre;
INSERT INTO COMUNA (com_nombre) VALUES ('Frutillar') ON DUPLICATE KEY UPDATE com_nombre=com_nombre;
INSERT INTO COMUNA (com_nombre) VALUES ('Fresia') ON DUPLICATE KEY UPDATE com_nombre=com_nombre;
INSERT INTO COMUNA (com_nombre) VALUES ('Los Muermos') ON DUPLICATE KEY UPDATE com_nombre=com_nombre;

-- Establecimientos (Ejemplos)
INSERT INTO ESTABLECIMIENTO (est_id, est_nombre, est_comunafk) VALUES 
-- FRESIA (4)
(7924, 'ESCUELA RURAL SAN ANDRES TEGUALDA', 4),
(7927, 'ESCUELA RURAL CAU-CAU', 4),
(7929, 'ESCUELA BASICA AGRICOLA HUEMPELEO', 4),
(7930, 'ESCUELA RURAL LUCILA GODOY ALCAYAGA', 4),
(7931, 'ESCUELA RURAL PATO LLICO', 4),
(7933, 'ESCUELA RURAL OLGA SOTO ALVARADO', 4),
(7938, 'ESCUELA RURAL ENTRE RIOS', 4),
(7939, 'ESCUELA RURAL LINEA SIN NOMBRE', 4),
(7940, 'ESCUELA RURAL PARGA', 4),
(7941, 'LICEO CARLOS IBAÑEZ DEL CAMPO', 4),
(7944, 'ESCUELA RURAL SANTA MONICA', 4),
(7945, 'ESCUELA RURAL PEUCHEN', 4),
(22105, 'ESCUELA BASICA FRESIA', 4),
(35132, 'JARDÍN INFANTIL CORAZON DE ANGEL', 4),
(35133, 'JARDÍN INFANTIL Y SALA CUNA EL RINCON DEL SABER', 4),

-- FRUTILLAR (3)
(7973, 'LICEO INDUSTRIAL CHILENO ALEMAN (LICHAF)', 3),
(7975, 'ESCUELA ARTURO ALESSANDRI PALMA', 3),
(7976, 'ESCUELA BERNARDO PHILIPPI', 3),
(7977, 'ESCUELA RURAL LOS LINARES DE CASMA', 3),
(7978, 'ESCUELA RURAL MARIO PEREZ NAVARRO', 3),
(7982, 'ESCUELA RURAL PARAGUAY', 3),
(7987, 'ESCUELA CARLOS SPRINGER NIKLITSCHEK', 3),
(7990, 'ESCUELA RURAL COLONIA SAN MARTIN', 3),
(11548, 'ESCUELA CLAUDIO MATTE', 3),
(22022, 'LICEO IGNACIO CARRERA PINTO', 3),
(22293, 'ESCUELA ESPECIAL SAN AGUSTIN', 3),
(22493, 'ESCUELA VICENTE PEREZ ROSALES', 3),
(35134, 'JARDÍN INFANTIL Y SALA CUNA FRUTILLITA', 3),
(35135, 'JARDÍN INFANTIL Y SALA CUNA PEQUEÑOS ANGELITOS', 3),
(35136, 'JARDÍN INFANTIL Y SALA CUNA MANITOS DE COLORES', 3),

-- LLANQUIHUE (1)
(7956, 'LICEO BICENTENARIO POLITECNICO HOLANDA', 1),
(7958, 'ESCUELA INES GALLARDO ALVARADO', 1),
(7959, 'ESCUELA BASICA GABRIELA MISTRAL', 1),
(7961, 'ESCUELA RURAL LOS PELLINES', 1),
(7962, 'ESCUELA RURAL LONCOTORO', 1),
(7966, 'ESCUELA RURAL LINEA SOLAR', 1),
(7967, 'ESCUELA RURAL COLEGUAL', 1),
(7968, 'ESCUELA RURAL COLIGUAL SAN JUAN', 1),
(35145, 'JARDÍN INFANTIL Y SALA CUNA MI PEQUEÑO PARAISO', 1),

-- LOS MUERMOS (5)
(7872, 'COLEGIO BICENTENARIO DE DIFUSION ARTISTICA LOS ULMOS', 5),
(7874, 'ESCUELA RURAL CAÑITAS', 5),
(7878, 'ESCUELA RURAL PALIHUE', 5),
(7879, 'ESCUELA RURAL QUILLAHUA', 5),
(7881, 'ESCUELA RURAL HUAUTRUNES', 5),
(7887, 'ESCUELA RURAL CARACOL', 5),
(7896, 'ESCUELA RURAL ESTAQUILLA', 5),
(7897, 'ESCUELA RURAL MANUEL GATICA ARRIAGADA', 5),
(7898, 'ESCUELA RURAL EL MELI', 5),
(7905, 'ESCUELA RURAL PARAGUAY CHICO', 5),
(22012, 'LICEO PUNTA DE RIELES', 5),
(22309, 'COLEGIO INGLÉS MABEL CONDEMARÍN', 5),
(22310, 'ESCUELA RURAL YERBAS BUENAS', 5),
(35137, 'JARDÍN INFANTIL Y SALA CUNA DUENDECITOS / CUMBRE ALTA', 5),
(35138, 'JARDÍN INFANTIL Y SALA CUNA SEMILLITAS DE AMOR', 5),
(35139, 'JARDÍN INFANTIL Y SALA CUNA BROTECITOS DEL MELI', 5),
(35140, 'JARDÍN INFANTIL Y SALA CUNA VENTANITAS DE COLORES', 5),

-- PUERTO VARAS (2)
(7720, 'LICEO BICENTENARIO DE EXCELENCIA PEDRO AGUIRRE CERDA', 2),
(7722, 'COLEGIO ROSITA NOVARO DE NOVARO', 2),
(7723, 'ESCUELA GRUPO ESCOLAR', 2),
(7724, 'COLEGIO NUEVA BRAUNAU', 2),
(7725, 'ESCUELA RURAL COLONIA RIO SUR', 2),
(7726, 'ESCUELA RURAL SANTA MARIA', 2),
(7729, 'ESCUELA RURAL JOSE WERNER MEIXNER', 2),
(7730, 'ESCUELA RURAL REINALDO RADDATZ HARRICH', 2),
(7732, 'ESCUELA RURAL JANEQUEO', 2),
(7738, 'ESCUELA RURAL HARDY MINTE BARTSCH', 2),
(7740, 'ESCUELA RURAL EPSON DE ENSENADA', 2),
(7741, 'ESCUELA RURAL RICARDO ROTH SCHUTZ', 2),
(7756, 'ESCUELA RURAL CRISTO REY', 2),
(7761, 'ESCUELA RURAL LAS CAMELIAS', 2),
(7765, 'ESCUELA RURAL LA PENINSULA', 2),
(8000, 'ESCUELA RURAL COLONIA TRES PUENTES', 2),
(22101, 'ESCUELA DIFERENCIAL ASPADEP', 2),
(22519, 'COLEGIO MIRADOR DEL LAGO', 2),
(35153, 'JARDÍN INFANTIL Y SALA CUNA ARCOIRIS', 2),
(35154, 'JARDÍN INFANTIL Y SALA CUNA MURTITAS DE ENSENADA', 2),
(35155, 'JARDÍN INFANTIL Y SALA CUNA MI NUEVA AVENTURA', 2),
(35156, 'SALA CUNA PRINCESA LICARAYEN', 2)
ON DUPLICATE KEY UPDATE est_nombre=est_nombre;
